# This is a basic workflow to help you get started with Actions

name: Firebase Hosting deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Download dependency
        run: yarn install

      - name: Set dotenv variables REACT_APP_API_KEY
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_API_KEY' # [Required]
          value: ${{secrets.REACT_APP_API_KEY}} # [Required]

      - name: Set dotenv variables REACT_APP_AUTH_DOMAIN
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_AUTH_DOMAIN' # [Required]
          value: ${{secrets.REACT_APP_AUTH_DOMAIN}} # [Required]

      - name: Set dotenv variables REACT_APP_DATABASE_URL
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_DATABASE_URL' # [Required]
          value: ${{secrets.REACT_APP_DATABASE_URL}} # [Required]

      - name: Set dotenv variables REACT_APP_PROJECT_ID
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_PROJECT_ID' # [Required]
          value: ${{secrets.REACT_APP_PROJECT_ID}} # [Required]

      - name: Set dotenv variables REACT_APP_STORAGEBUCKET
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_STORAGEBUCKET' # [Required]
          value: ${{secrets.REACT_APP_STORAGEBUCKET}} # [Required]

      - name: Set dotenv variables REACT_APP_MESSAGING_SENDER_ID
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_MESSAGING_SENDER_ID' # [Required]
          value: ${{secrets.REACT_APP_MESSAGING_SENDER_ID}} # [Required]

      - name: Set dotenv variables REACT_APP_APP_ID
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_APP_ID' # [Required]
          value: ${{secrets.REACT_APP_APP_ID}} # [Required]

      - name: Set dotenv variables REACT_APP_BASE_URL
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_BASE_URL' # [Required]
          value: ${{secrets.REACT_APP_BASE_URL}} # [Required]


      - name: Build application
        run: yarn build


      - name: Firebase hosting deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --public ./build --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
